# Generated by Django 5.2.7 on 2025-11-09 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEntrenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('dataset_usado', models.CharField(blank=True, max_length=255)),
                ('precision_modelo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField()),
                ('ventas_estimadas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodo', models.CharField(max_length=20)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.modeloentrenado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.producto')),
            ],
            options={
                'ordering': ['-fecha_prediccion'],
            },
        ),
    ]
